services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    command: ["sh", "-c", "alembic upgrade head && make run-deploy"]
    tty: true
    volumes:
      - ./app:/app:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
    ports:
      - 8080:8080

volumes:
  db-data:
  test-db-data: