"""Initial migration

Revision ID: d8787ac95ebb
Revises:
Create Date: 2025-02-21 15:07:09.246959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8787ac95ebb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ipgeolocation",
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("continent_code", sa.String(), nullable=True),
        sa.Column("continent_name", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(), nullable=True),
        sa.Column("country_name", sa.String(), nullable=True),
        sa.Column("region_code", sa.String(), nullable=True),
        sa.Column("region_name", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("zip", sa.String(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=16, scale=13), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=16, scale=13), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ipgeolocation_ip"), "ipgeolocation", ["ip"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ipgeolocation_ip"), table_name="ipgeolocation")
    op.drop_table("ipgeolocation")
    # ### end Alembic commands ###
